version: "3"
services:
  mongo:
    image: mongo
    hostname: localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: communere
      MONGO_INITDB_ROOT_PASSWORD: communere
    ports:
      - 27017:27017
    restart: always
