version: "3.1"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: communere
      MONGO_INITDB_ROOT_PASSWORD: communere
    ports:
      - "27017:27017"
    restart: always
  app:
    build: .
    depends_on:
      - mongo
    environment:
      PORT: 5500
      MONGO_USER: communere
      MONGO_PASS: communere
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    ports:
      - "5500:5500"
  web:
    build: ./nginx
    container_name: reverse
    depends_on:
      - app
    ports:
      - "8080:80"
